apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: 이메일아이디-upload 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: 이메일아이디-upload
    spec:
      containers:
      - name: 이메일아이디-upload 
        image: 본인 ACR 주소를 입력해주세요./이메일아이디-upload:latest
        ports:
        - containerPort: 4000 
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: 이메일아이디-upload 
spec:
  type: LoadBalancer
  ports:
  - port: 4000 
  selector:
    app: 이메일아이디-upload 
