apiVersion: apps/v1
kind: Deployment
metadata:
  name: [emailid]-upload 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: [emailid]-upload
    spec:
      containers:
      - name: [emailid]-upload 
        image: [acr-login-server]/[emailid]-upload:latest
        ports:
        - containerPort: 4000 
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: [emailid]-upload 
spec:
  type: LoadBalancer
  ports:
  - port: 80 
    targetPort: 4000
  selector:
    app: [emailid]-upload 
