apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: [emailid]-worker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: [emailid]-worker 
    spec:
      containers:
      - name: [emailid]-worker 
        image: [acr-login-server]/[emailid]-worker:latest
        ports:
        - containerPort: 4000 
      imagePullSecrets:
      - name: acr-auth
---
